---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: educates-sa
  namespace: eduk8s-ctrl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-package-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: educates-sa
    namespace: eduk8s-ctrl
